"""relate users to books

Revision ID: 811722d071f0
Revises: 2f965b89da0e
Create Date: 2025-05-02 10:16:39.728392

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "811722d071f0"
down_revision: Union[str, None] = "2f965b89da0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("user_uid", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "books", "users", ["user_uid"], ["uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.drop_column("books", "user_uid")
    # ### end Alembic commands ###
